### ISSUE TITLE
είμαι verb conjugation is timing out

### ISSUE THREAD

**Issue by msooklaris** [tsouchlarakis/greek-verbs#4]
I tried to run this command, and it timed out. 
`greek-verbs anki-flashcard --verb είμαι --num-examples 3`

This was the response in the terminal. 
`Killed: 9`

I looked manually in the greek-verbs.json and found that the verb did have an entry.

**Comment by tsouchlarakis** [comment]
This is not reproducible for me. Could you try restarting terminal and any virtual environments and try again?

**Comment by msooklaris** [comment]
I restarted and I'm seeing the same issue

**Comment by msooklaris** [comment]
seeing the same issue with έχω

**Comment by tsouchlarakis** [comment]
This was fixed a while ago.
